#!/bin/sh
HERE="$(dirname "$(readlink -f "$0")")"
export PYTHONNOUSERSITE=1
export PYTHONDONTWRITEBYTECODE=1
export PYTHONPATH="$HERE/usr/lib/python3.14/site-packages"
exec "$HERE/usr/bin/python3.14" "$HERE/usr/bin/apic" "$@"

